### PR TITLE
FYI: Research effort to generalize zephyr_arduino101 target to just zephyr

### PR DESCRIPTION
**Pull request by pfalcon**
Hello @sergioamr , FYI, I was hacking around to generalize your code to at least be able to build qemu_cortex_m3. The biggest outcome so far is me seeing issues with extensibility of Zephyr build system, and trying to communicate them to Zephyr upstream. I'd appreciate if you could have a look at my comments to https://jira.zephyrproject.org/browse/ZEP-366 and see if it makes sense to you and if you agree with proposed solution (I would like to apologize beforehand if what's written sounds like critics to the way you've done this port - that's not intention at all, my point is that Zephyr build system so far such that it literal calls for doing things in unclear and buggy way, and it's pretty hard to debug them).

I actually wanted to submit this as an issue ticket, not pull request, but issue tracker is not enabled in your fork, so I submit PR instead.

Thanks!

### CODE REVIEW

**Comment by sergioamr** [comment]
Hi Paul!,

No worries, I just landed in the project a few weeks ago so I am not that familiar with either Jerryscript nor Zephyr.
I needed to get an integration of Zephyr with Arduino 101 without modifying any of the build systems.
I did not intend to support other architectures at that precise moment since my project is specific to Curie/Arduino101.

Sometimes you need a use case to move a project forward in a direction and my understanding is that Zephyr has been historically very application centric not allowing libraries to be linked.

My team did an early integration with Jerryscript and it was quite difficult to use so I built this one to get myself familiar with the project and also being able to get something upstream so we can start this discussion and have some work done.

Thanks for looking at it and commenting :D

Sergio

**Comment by sergioamr** [comment]
I think it is sound and you should try to get it upstream. Specially the USER_LIBS instead of the TOOLCHAIN_LIBS, I had it on my todo list to do that.

At some point if this integration becomes generic it could be a good idea to rename the folder from arduino101 to zephyr.

This branch was merged already with upstream:
https://github.com/Samsung/jerryscript/pull/1108

If you could rebase with upstream, squash the commit and add the signed off in this format:
JerryScript-DCO-1.0-Signed-off-by: 

Thanks for looking at this, i know the Zephyr guys were dragging a bit their feet on adding support for external libraries and jerryscript has a lot to be configured to fit it compiled using the application approach.

**Comment by pfalcon** [comment]
@sergioamr : Thanks for response, helpful hints, and link to the upstream pull request. I'll rebase my patches against upstream then. From comments to https://jira.zephyrproject.org/browse/ZEP-366 got an idea that something is cooking on Zephyr side provide "official" way to integrate with 3rd-party libs. I'd wait a bi to see if anything surfaces and will be easily applicable to JerryScript, and if not, indeed would submit my patchset as is.

Do you intend to continue work on jerryscript/zephyr port, or is it all you wanted to have done so far?

Thanks!

**Comment by sergioamr** [comment]
@pfalcon I am working on uploading Javascript/Ecmascript code directly to the Arduino101 using the USB and DFU, that requires some bits and pieces from the original firmware. I will evolve this port further after we get some idea of what do they decide to do from the Zephyr side. 

I am aware that they are looking into this use case and it makes sense to keep it up to date with whatever they change.

**Comment by pfalcon** [comment]
@sergioamr : Nice, my interest would be in improving interactive prompt and looking into running a testsuite on a target, so I'll know there won't be duplication of effort.

**Comment by sergioamr** [comment]
@pfalcon @Akromx16 is adding support for Travis integration using qemu. We just got the initial build of qemu_x86 and ran the test example yesterday.

I believe this is the branch:
https://github.com/Akromx16/jerryscript/commits/wip_sergio_travis_2

The plan on that side is to change the interactive shell to be able to run a full script and not parse the command line shell as parameters, since it was just a quick and dirty approach. Although if you get that bit done he will not have to do it :-D

**Comment by sergioamr** [comment]
@pfalcon That is his latest version, still wip.
https://github.com/Akromx16/jerryscript/tree/wip/adrian_travis

**Comment by pfalcon** [comment]
@sergioamr , @Akromx16 : Thanks for the pointers. I'm pretty new to JerryScript too, so it may take me some time to get up to speed with it and do that, but I'll keep in mind that Travis integration is already in works.

In the meantime, I rebased my patches on JS master: https://github.com/pfalcon/jerryscript/commits/zephyr-portable . And I guess the best thing I can do is indeed to submit them asap.

**Pull request closed without merging**
